// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/noho-digital/genny

package errorx

import (
	"fmt"
	"math/rand"
	"strings"
	"sync"

	"github.com/pkg/errors"
)

type ErrorSlice []error
type ErrorSliceReduceOption func(*ErrorSliceReduceOptions)
type ErrorSliceReduceOptions struct {
	initial error
}

type ErrorSliceAsyncOption func(options *ErrorSliceAsyncOptions)
type ErrorSliceAsyncOptions struct {
	PoolSize int
}

func NewErrorSlice(items ...error) ErrorSlice {
	slice := make(ErrorSlice, len(items))
	for i, item := range items {
		slice[i] = item
	}
	return slice
}

func WithInitialError(t error) ErrorSliceReduceOption {
	return func(o *ErrorSliceReduceOptions) {
		o.initial = t
	}
}

func WhereErrorAll(pl ...func(error) bool) func(error) bool {
	return func(t error) bool {
		for _, p := range pl {
			if !p(t) {
				return false
			}
		}
		return true
	}
}

func WhereErrorAny(pl ...func(error) bool) func(error) bool {
	return func(t error) bool {
		for _, p := range pl {
			if p(t) {
				return true
			}
		}
		return false
	}
}

func WhereErrorNot(p func(error) bool) func(error) bool {
	return func(t error) bool {
		return !p(t)
	}
}

func (slice ErrorSlice) Index(item error) int {
	for i, t := range slice {
		if item == t {
			return i
		}
	}
	return -1
}

// Returns copy of slice with only items that have non-default values
// (e.g. for pointer types all non-nil items)
func (slice ErrorSlice) Compact() ErrorSlice {
	var dfl error
	s := NewErrorSlice()
	for _, t := range slice {
		if t == dfl {
			continue
		}
		s = append(s, t)
	}
	return s
}

func (slice ErrorSlice) Map(fn func(error) error) ErrorSlice {
	mapped := make(ErrorSlice, len(slice))
	for i, t := range slice {
		mapped[i] = fn(t)
	}
	return mapped
}

func (slice ErrorSlice) AsyncMap(fn func(error) error, options ...ErrorSliceAsyncOption) ErrorSlice {
	output := make(ErrorSlice, len(slice))
	eachFn := func(t error, i int) {
		v := fn(t)
		output[i] = v
	}
	slice.AsyncEachIndex(eachFn, options...)
	return output
}

func (slice ErrorSlice) MapString(fn func(error) string) []string {
	mapped := make([]string, len(slice))
	for i, t := range slice {
		mapped[i] = fn(t)
	}
	return mapped
}

func (slice ErrorSlice) AsyncMapString(fn func(error) string, options ...ErrorSliceAsyncOption) []string {
	output := make([]string, len(slice))
	eachFn := func(t error, i int) {
		v := fn(t)
		output[i] = v
	}
	slice.AsyncEachIndex(eachFn, options...)
	return output
}

func (slice ErrorSlice) MapBool(fn func(error) bool) []bool {
	mapped := make([]bool, len(slice))
	for i, t := range slice {
		mapped[i] = fn(t)
	}
	return mapped
}

func (slice ErrorSlice) AsyncMapBool(fn func(error) bool, options ...ErrorSliceAsyncOption) []bool {
	output := make([]bool, len(slice))
	eachFn := func(t error, i int) {
		v := fn(t)
		output[i] = v
	}
	slice.AsyncEachIndex(eachFn, options...)
	return output
}

func (slice ErrorSlice) Filter(where func(error) bool, ands ...func(error) bool) ErrorSlice {
	if len(ands) > 0 {
		where = WhereErrorAll(append([]func(error) bool{where}, ands...)...)
	}
	var selected ErrorSlice
	for _, t := range slice {
		if where(t) {
			selected = append(selected, t)
		}
	}
	return selected
}

func (slice ErrorSlice) Reversed() ErrorSlice {
	s2 := make(ErrorSlice, len(slice))
	for i, j := 0, len(slice)-1; i < j; i, j = i+1, j-1 {
		s2[i] = slice[j]
	}
	r := slice.Copy()
	r.Reverse()
	return r
}

func (slice ErrorSlice) Reverse() {
	for i, j := 0, len(slice)-1; i < j; i, j = i+1, j-1 {
		slice[i], slice[j] = slice[j], slice[i]
	}
}

func (slice ErrorSlice) ReverseSelect(where func(error) bool, ands ...func(error) bool) ErrorSlice {
	if len(ands) > 0 {
		where = WhereErrorAll(append([]func(error) bool{where}, ands...)...)
	}
	var selected ErrorSlice
	for i := len(slice) - 1; i >= 0; i-- {
		t := slice[i]
		if where(t) {
			selected = append(selected, t)
		}
	}
	return selected
}

func (slice ErrorSlice) IndexSelect(p func(error) bool) []int {
	var indexes []int
	for i, t := range slice {
		if p(t) {
			indexes = append(indexes, i)
		}
	}
	return indexes
}

// safe index access -- allows negative indexing, and will error instead of panic if out of bounds
func (slice ErrorSlice) Item(index int) (item error, err error) {
	if index < 0 {
		index = len(slice) - index
	}
	if index < 0 || index > len(slice)+1 {
		err = fmt.Errorf("index out of range")
	} else {
		item = slice[index]
	}
	return item, err
}

func (slice ErrorSlice) SelectAsync(p func(error) bool) ErrorSlice {
	var selected ErrorSlice
	hits := slice.AsyncMapBool(p)
	for i, t := range slice {
		if hits[i] {
			selected = append(selected, t)
		}
	}
	return selected
}

func (slice ErrorSlice) Reject(p func(error) bool) ErrorSlice {
	return slice.Filter(func(t error) bool { return !p(t) })
}

func (slice ErrorSlice) Reduce(operator func(error, error) error, options ...ErrorSliceReduceOption) (result error) {
	o := &ErrorSliceReduceOptions{}
	for _, opt := range options {
		opt(o)
	}
	result = o.initial
	for _, next := range slice {
		result = operator(result, next)
	}
	return result
}

// If no predicate function parameters given returns true if slice is not empty.
// Otherwise, will walk the slice backwards and return true for the first item where all the predicates
// return true
func (slice ErrorSlice) ReverseAny(criteria ...func(error) bool) bool {
	if len(criteria) == 0 {
		return len(slice) > 0
	}
	p := WhereErrorAll(criteria...)
	for i := len(slice) - 1; i >= 0; i-- {
		t := slice[i]
		if p(t) {
			return true
		}
	}
	return false
}

// If no predicate function parameters given returns true if slice is not empty.
// Otherwise, will return true if all predicate function parameters return true for any item in the slice
func (slice ErrorSlice) Any(pl ...func(error) bool) bool {
	if len(pl) == 0 {
		return len(slice) > 0
	}
	p := WhereErrorAll(pl...)
	for _, t := range slice {
		if p(t) {
			return true
		}
	}
	return false
}

func (slice ErrorSlice) ContainsAll(items ...error) bool {
	for _, item := range items {
		itemMatch := false
		for _, t := range slice {
			if item == t {
				itemMatch = true
				break
			}
		}
		if !itemMatch {
			return false
		}
	}
	return true
}

func (slice ErrorSlice) ContainsAny(items ...error) bool {
	for _, t := range slice {
		for _, item := range items {
			if item == t {
				return true
			}
		}
	}
	return false
}

func (slice ErrorSlice) PopLast() (last error, rest ErrorSlice) {
	l := len(slice)
	if l > 0 {
		last = slice[len(slice)-1]
	}
	if l > 1 {
		rest = slice[0 : len(slice)-1]
	}
	return last, rest
}

func (slice ErrorSlice) PopFirst() (first error, rest ErrorSlice) {
	l := len(slice)
	if l > 0 {
		first = slice[0]
	}
	if l > 1 {
		rest = slice[1:]
	}
	return first, rest
}

func (slice ErrorSlice) String() string {
	if slice == nil {
		return fmt.Sprint(nil)
	}
	return fmt.Sprintf("[%v]", strings.Join(slice.Strings(), ", "))
}

func (slice ErrorSlice) Strings() []string {
	return slice.MapString(func(x error) string {
		return fmt.Sprintf("%v", x)
	})
}
func (slice ErrorSlice) Pop(index int) (popped error, rest ErrorSlice) {
	if index < 0 {
		index = len(slice) - index
	}
	if index <= 0 {
		return slice.PopFirst()
	}
	if index >= len(slice)-1 {
		return slice.PopLast()
	}
	for i, item := range slice {
		if i == index {
			popped = item
		} else {
			rest = append(rest, item)
		}
	}
	return popped, rest
}

func (slice ErrorSlice) Contains(item error) bool {
	for _, t := range slice {
		if item == t {
			return true
		}
	}
	return false
}

func (slice ErrorSlice) AnyNot(pl ...func(error) bool) bool {
	return !slice.Any(pl...)
}

func (slice ErrorSlice) All(p func(error) bool) bool {
	for _, t := range slice {
		if !p(t) {
			return false
		}
	}
	return true
}

func (slice ErrorSlice) AllNot(p func(error) bool) bool {
	return !slice.All(p)
}

func (slice ErrorSlice) Append(items ...error) ErrorSlice {
	if slice == nil {
		var empty ErrorSlice
		return append(empty, items...)
	}
	return append(slice, items...)
}

func (slice ErrorSlice) Count(p func(error) bool) int {
	return len(slice.Filter(p))
}

func (slice ErrorSlice) Equal(other []error) bool {
	if len(slice) != len(other) {
		return false
	}
	for n := range slice {
		if slice[n] != other[n] {
			return false
		}
	}
	return true
}

func (slice ErrorSlice) Last(where ...func(error) bool) (last error) {
	hasCriteria := len(where) > 0
	matchesCriteria := WhereErrorAll(where...)
	for i := len(slice) - 1; i >= 0; i-- {
		t := slice[i]
		if !hasCriteria || matchesCriteria(t) {
			last = t
			break
		}
	}
	return last
}

func (slice ErrorSlice) First(where ...func(error) bool) (first error) {
	hasCriteria := len(where) > 0
	matchesCriteria := WhereErrorAll(where...)
	for _, t := range slice {
		if !hasCriteria || matchesCriteria(t) {
			first = t
			break
		}
	}
	return first
}

func (slice ErrorSlice) FirstIndex(where ...func(error) bool) int {
	if len(slice) == 0 {
		return -1
	}
	p := WhereErrorAll(where...)
	for i, t := range slice {
		if p(t) {
			return i
		}
	}
	return -1
}

func (slice ErrorSlice) DistinctBy(match func(error, error) bool) (result ErrorSlice) {
Outer:
	for _, v := range slice {
		for _, r := range result {
			if match(v, r) {
				continue Outer
			}
		}
		result = append(result, v)
	}
	return result
}

func (slice ErrorSlice) Len() int {
	return len(slice)
}

func (slice ErrorSlice) Each(f func(error)) {
	for _, t := range slice {
		f(t)
	}
}

func (slice ErrorSlice) AsyncEach(f func(error), options ...ErrorSliceAsyncOption) {
	slice.AsyncEachIndex(func(t error, _ int) {
		f(t)
	}, options...)
}

func WithErrorAsyncPoolSize(size int) ErrorSliceAsyncOption {
	return func(options *ErrorSliceAsyncOptions) {
		options.PoolSize = size
	}
}

func newErrorSliceAsyncOptions(opts ...ErrorSliceAsyncOption) *ErrorSliceAsyncOptions {
	o := &ErrorSliceAsyncOptions{PoolSize: -1}
	for _, opt := range opts {
		opt(o)
	}
	return o
}

func (slice ErrorSlice) AsyncEachIndex(f func(error, int), options ...ErrorSliceAsyncOption) {
	o := newErrorSliceAsyncOptions(options...)
	if o.PoolSize <= 0 {
		wg := &sync.WaitGroup{}
		for index, item := range slice {
			wg.Add(1)
			go func(item error, index int) {
				f(item, index)
				wg.Done()
			}(item, index)
		}
		wg.Wait()
		return
	}
	pending := make(chan int, len(slice))
	completed := make(chan int, len(slice))
	for w := 0; w < o.PoolSize; w++ {
		go func(slice ErrorSlice, f func(error, int), pending <-chan int, completed chan<- int) {
			for index := range pending {
				item := slice[index]
				f(item, index)
				completed <- index
			}
		}(slice, f, pending, completed)
	}
	for index := range slice {
		pending <- index
	}
	close(pending)
	for range slice {
		<-completed
	}
}

func (slice ErrorSlice) EachIndex(f func(error, int)) {
	for i, t := range slice {
		f(t, i)
	}
}

func (slice ErrorSlice) Swap(i, j int) {
	slice[i], slice[j] = slice[j], slice[i]
}

func (slice ErrorSlice) Empty() bool {
	return len(slice) == 0
}

func (slice ErrorSlice) NotEmpty() bool {
	return len(slice) > 0
}

func (slice ErrorSlice) AsyncCopy() ErrorSlice {
	cp := make(ErrorSlice, len(slice))
	slice.AsyncEachIndex(func(_ error, i int) {
		cp[i] = slice[i]
	})
	return cp
}

func (slice ErrorSlice) Copy() ErrorSlice {
	cp := make(ErrorSlice, len(slice))
	for i := range slice {
		cp[i] = slice[i]
	}
	return cp
}

func (slice ErrorSlice) SortBy(less func(error, error) bool) {

	// Switch to heapsort if depth of 2*ceil(lg(n+1)) is reached.
	n := len(slice)
	maxDepth := 0
	for i := n; i > 0; i >>= 1 {
		maxDepth++
	}
	maxDepth *= 2
	__quickSortErrorSlice(slice, less, 0, n, maxDepth)
}

func (slice ErrorSlice) SortedBy(less func(error, error) bool) ErrorSlice {
	cp := slice.Copy()
	cp.SortBy(less)
	return cp
}

func (slice ErrorSlice) IsSortedBy(less func(error, error) bool) bool {
	n := len(slice)
	for i := n - 1; i > 0; i-- {
		if less(slice[i], slice[i-1]) {
			return false
		}
	}
	return true
}

func (slice ErrorSlice) SortDescBy(less func(error, error) bool) {
	greater := func(a, b error) bool {
		return less(b, a)
	}
	slice.SortBy(greater)
}

func (slice ErrorSlice) SortedDescBy(less func(error, error) bool) ErrorSlice {
	greater := func(a, b error) bool {
		return less(b, a)
	}
	return slice.SortedBy(greater)
}

func (slice ErrorSlice) IsSortedDescBy(less func(error, error) bool) bool {
	greater := func(a, b error) bool {
		return less(b, a)
	}
	return slice.IsSortedBy(greater)
}

// Shuffled returns a copy of ErrorSlice with the contents shuffles using a version of the Fisher-Yates shuffle. See: http://clipperhouse.github.io/gen/#Shuffle
func (slice ErrorSlice) Shuffled() ErrorSlice {
	s := slice.Copy()
	s.Shuffle()
	return s
}

// Shuffle shuffles the contents of ErrorSlice in place using a version of the Fisher-Yates shuffle. See: http://clipperhouse.github.io/gen/#Shuffle
func (slice ErrorSlice) Shuffle() {
	total := len(slice)
	for i := 0; i < total; i++ {
		r := i + rand.Intn(total-i)
		slice[r], slice[i] = slice[i], slice[r]
	}
}

// MaxBy returns an element of ErrorSlice containing the maximum value, when compared to other elements using a passed func defining ‘less’. In the case of multiple items being equally maximal, the last such element is returned. Returns error if no elements. See: http://clipperhouse.github.io/gen/#MaxBy
func (slice ErrorSlice) MaxBy(less func(error, error) bool) (result error, err error) {
	l := len(slice)
	if l == 0 {
		err = errors.New("cannot determine the MaxBy of an empty slice")
		return
	}
	m := 0
	for i := 1; i < l; i++ {
		if !less(slice[i], slice[m]) {
			m = i
		}
	}
	result = slice[m]
	return
}

// MinBy returns an element of ErrorSlice containing the minimum value, when compared to other elements using a passed func defining ‘less’. In the case of multiple items being equally minimal, the first such element is returned. Returns error if no elements. See: http://clipperhouse.github.io/gen/#MinBy
func (slice ErrorSlice) MinBy(less func(error, error) bool) (result error, err error) {
	l := len(slice)
	if l == 0 {
		err = errors.New("cannot determine the Min of an empty slice")
		return
	}
	m := 0
	for i := 1; i < l; i++ {
		if less(slice[i], slice[m]) {
			m = i
		}
	}
	result = slice[m]
	return
}

func (slice ErrorSlice) AsyncReplaced(fn func(t error) error) ErrorSlice {
	s := slice.Copy()
	s.AsyncReplace(fn)
	return s
}

func (slice ErrorSlice) Replaced(fn func(t error) error) ErrorSlice {
	s := slice.Copy()
	s.Replace(fn)
	return s
}

func (slice ErrorSlice) Replace(fn func(t error) error) {
	for i, t := range slice {
		slice[i] = fn(t)
	}
}

func (slice ErrorSlice) AsyncReplace(fn func(t error) error, options ...ErrorSliceAsyncOption) {
	slice.AsyncEachIndex(func(t error, i int) {
		slice[i] = fn(t)
	}, options...)
}

func (slice ErrorSlice) SkipTake(skip, take int) ErrorSlice {
	var out ErrorSlice
	skipped := 0
	taken := 0
	for _, item := range slice {
		if skip > skipped {
			skipped++
			continue
		}
		out = append(out, item)
		taken++
		if take > 0 && taken >= take {
			break
		}
	}
	return out

}
func (slice ErrorSlice) Split(fn func(t error) bool) (ErrorSlice, ErrorSlice) {
	var a ErrorSlice
	var b ErrorSlice
	for _, t := range slice {
		if fn(t) {
			a = append(a, t)
		} else {
			b = append(b, t)
		}
	}
	return a, b
}

func __swapErrorSlice(slice ErrorSlice, a, b int) {
	slice[a], slice[b] = slice[b], slice[a]
}

// Insertion sort
func __insertionSortErrorSlice(slice ErrorSlice, less func(error, error) bool, a, b int) {
	for i := a + 1; i < b; i++ {
		for j := i; j > a && less(slice[j], slice[j-1]); j-- {
			__swapErrorSlice(slice, j, j-1)
		}
	}
}

// siftDown implements the heap property on slice[lo, hi).
// first is an offset into the array where the root of the heap lies.
func __siftDownErrorSlice(slice ErrorSlice, less func(error, error) bool, lo, hi, first int) {
	root := lo
	for {
		child := 2*root + 1
		if child >= hi {
			break
		}
		if child+1 < hi && less(slice[first+child], slice[first+child+1]) {
			child++
		}
		if !less(slice[first+root], slice[first+child]) {
			return
		}
		__swapErrorSlice(slice, first+root, first+child)
		root = child
	}
}
func __heapSortErrorSlice(slice ErrorSlice, less func(error, error) bool, a, b int) {
	first := a
	lo := 0
	hi := b - a
	// Build heap with greatest element at top.
	for i := (hi - 1) / 2; i >= 0; i-- {
		__siftDownErrorSlice(slice, less, i, hi, first)
	}
	// Pop elements, largest first, into end of slice.
	for i := hi - 1; i >= 0; i-- {
		__swapErrorSlice(slice, first, first+i)
		__siftDownErrorSlice(slice, less, lo, i, first)
	}
}

// Quicksort, following Bentley and McIlroy,
// Engineering a Sort Function, SP&E November 1993.
// medianOfThree moves the median of the three values slice[a], slice[b], slice[c] into slice[a].
func __medianOfThreeErrorSlice(slice ErrorSlice, less func(error, error) bool, a, b, c int) {
	m0 := b
	m1 := a
	m2 := c
	// bubble sort on 3 elements
	if less(slice[m1], slice[m0]) {
		__swapErrorSlice(slice, m1, m0)
	}
	if less(slice[m2], slice[m1]) {
		__swapErrorSlice(slice, m2, m1)
	}
	if less(slice[m1], slice[m0]) {
		__swapErrorSlice(slice, m1, m0)
	}
	// now slice[m0] <= slice[m1] <= slice[m2]
}

func __swapRangeErrorSlice(slice ErrorSlice, a, b, n int) {
	for i := 0; i < n; i++ {
		__swapErrorSlice(slice, a+i, b+i)
	}
}
func __doPivotErrorSlice(slice ErrorSlice, less func(error, error) bool, lo, hi int) (midlo, midhi int) {
	m := lo + (hi-lo)/2 // Written like this to avoid integer overflow.
	if hi-lo > 40 {
		// Tukey's Ninther, median of three medians of three.
		s := (hi - lo) / 8
		__medianOfThreeErrorSlice(slice, less, lo, lo+s, lo+2*s)
		__medianOfThreeErrorSlice(slice, less, m, m-s, m+s)
		__medianOfThreeErrorSlice(slice, less, hi-1, hi-1-s, hi-1-2*s)
	}
	__medianOfThreeErrorSlice(slice, less, lo, m, hi-1)
	// Invariants are:
	//	slice[lo] = pivot (set up by ChoosePivot)
	//	slice[lo <= i < a] = pivot
	//	slice[a <= i < b] < pivot
	//	slice[b <= i < c] is unexamined
	//	slice[c <= i < d] > pivot
	//	slice[d <= i < hi] = pivot
	//
	// Once b meets c, can swap the "= pivot" sections
	// into the middle of the slice.
	pivot := lo
	a, b, c, d := lo+1, lo+1, hi, hi
	for {
		for b < c {
			if less(slice[b], slice[pivot]) { // slice[b] < pivot
				b++
			} else if !less(slice[pivot], slice[b]) { // slice[b] = pivot
				__swapErrorSlice(slice, a, b)
				a++
				b++
			} else {
				break
			}
		}
		for b < c {
			if less(slice[pivot], slice[c-1]) { // slice[c-1] > pivot
				c--
			} else if !less(slice[c-1], slice[pivot]) { // slice[c-1] = pivot
				__swapErrorSlice(slice, c-1, d-1)
				c--
				d--
			} else {
				break
			}
		}
		if b >= c {
			break
		}
		// slice[b] > pivot; slice[c-1] < pivot
		__swapErrorSlice(slice, b, c-1)
		b++
		c--
	}
	min := func(a, b int) int {
		if a < b {
			return a
		}
		return b
	}
	n := min(b-a, a-lo)
	__swapRangeErrorSlice(slice, lo, b-n, n)
	n = min(hi-d, d-c)
	__swapRangeErrorSlice(slice, c, hi-n, n)
	return lo + b - a, hi - (d - c)
}

func __quickSortErrorSlice(slice ErrorSlice, less func(error, error) bool, a, b, maxDepth int) {
	for b-a > 7 {
		if maxDepth == 0 {
			__heapSortErrorSlice(slice, less, a, b)
			return
		}
		maxDepth--
		mlo, mhi := __doPivotErrorSlice(slice, less, a, b)
		// Avoiding recursion on the larger subproblem guarantees
		// a stack depth of at most lg(b-a).
		if mlo-a < b-mhi {
			__quickSortErrorSlice(slice, less, a, mlo, maxDepth)
			a = mhi // i.e., quickSortErrorSlice(slice, mhi, b)
		} else {
			__quickSortErrorSlice(slice, less, mhi, b, maxDepth)
			b = mlo // i.e., quickSortErrorSlice(slice, a, mlo)
		}
	}
	if b-a > 1 {
		__insertionSortErrorSlice(slice, less, a, b)
	}
}
